# Generated by Django 5.1.5 on 2025-02-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Program',
        ),
    ]
