# Generated by Django 5.1.5 on 2025-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
