# Generated by Django 5.1.5 on 2025-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_resumption_date_term_beginning_of_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='resumption_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
