# Generated by Django 5.1.5 on 2025-02-19 11:33

import main_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_result_resultsummary_delete_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.attendance',),
        ),
        migrations.CreateModel(
            name='AttendanceReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.attendancereport',),
        ),
        migrations.CreateModel(
            name='CustomUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.customuser',),
            managers=[
                ('objects', main_app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStaffProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback (Staff)',
                'verbose_name_plural': 'Feedback (Staff)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.feedbackstaff',),
        ),
        migrations.CreateModel(
            name='FeedbackStudentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback (Student)',
                'verbose_name_plural': 'Feedback (Student)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.feedbackstudent',),
        ),
        migrations.CreateModel(
            name='LeaveReportStaffProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Leave Report (Staff)',
                'verbose_name_plural': 'Leave Reports (Staff)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.leavereportstaff',),
        ),
        migrations.CreateModel(
            name='LeaveReportStudentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Leave Report (Student)',
                'verbose_name_plural': 'Leave Reports (Student)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.leavereportstudent',),
        ),
        migrations.CreateModel(
            name='NotificationStaffProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Notification (Staff)',
                'verbose_name_plural': 'Notifications (Staff)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.notificationstaff',),
        ),
        migrations.CreateModel(
            name='NotificationStudentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Notification (Student)',
                'verbose_name_plural': 'Notifications (Student)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.notificationstudent',),
        ),
        migrations.CreateModel(
            name='ProgramProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.program',),
        ),
        migrations.CreateModel(
            name='ResultProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.result',),
        ),
        migrations.CreateModel(
            name='ResultSummaryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Result Summary',
                'verbose_name_plural': 'Result Summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.resultsummary',),
        ),
        migrations.CreateModel(
            name='SessionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.session',),
        ),
        migrations.CreateModel(
            name='StaffProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.staff',),
        ),
        migrations.CreateModel(
            name='StudentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.student',),
        ),
        migrations.CreateModel(
            name='SubjectProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.subject',),
        ),
    ]
