# Generated by Django 5.1.5 on 2025-03-21 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_term_resumption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resultsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
