# Generated by Django 5.1.5 on 2025-03-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_resultsummary_created_at_resultsummary_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
