# Generated by Django 5.1.5 on 2025-03-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.term',),
        ),
    ]
