# Generated by Django 5.1.5 on 2025-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_termproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
