# Generated by Django 5.1.5 on 2025-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_notificationstaff_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
